// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/translate/v3/translation_service.proto

package com.google.cloud.translate.v3;

public interface DetectLanguageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.translation.v3.DetectLanguageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of detected languages sorted by detection confidence in descending
   * order. The most probable language first.
   * </pre>
   *
   * <code>repeated .google.cloud.translation.v3.DetectedLanguage languages = 1;</code>
   */
  java.util.List<com.google.cloud.translate.v3.DetectedLanguage> 
      getLanguagesList();
  /**
   * <pre>
   * A list of detected languages sorted by detection confidence in descending
   * order. The most probable language first.
   * </pre>
   *
   * <code>repeated .google.cloud.translation.v3.DetectedLanguage languages = 1;</code>
   */
  com.google.cloud.translate.v3.DetectedLanguage getLanguages(int index);
  /**
   * <pre>
   * A list of detected languages sorted by detection confidence in descending
   * order. The most probable language first.
   * </pre>
   *
   * <code>repeated .google.cloud.translation.v3.DetectedLanguage languages = 1;</code>
   */
  int getLanguagesCount();
  /**
   * <pre>
   * A list of detected languages sorted by detection confidence in descending
   * order. The most probable language first.
   * </pre>
   *
   * <code>repeated .google.cloud.translation.v3.DetectedLanguage languages = 1;</code>
   */
  java.util.List<? extends com.google.cloud.translate.v3.DetectedLanguageOrBuilder> 
      getLanguagesOrBuilderList();
  /**
   * <pre>
   * A list of detected languages sorted by detection confidence in descending
   * order. The most probable language first.
   * </pre>
   *
   * <code>repeated .google.cloud.translation.v3.DetectedLanguage languages = 1;</code>
   */
  com.google.cloud.translate.v3.DetectedLanguageOrBuilder getLanguagesOrBuilder(
      int index);
}
